### ISSUE TITLE
Question about persisting the user on refresh

### ISSUE THREAD

**Issue by JeremyCarlsten** [wshirey/multivision#1]
I have run into an issue with the browser refresh, it appears as though the request object doesn't contain the user.  I haven't yet gone through your code to compare them but I was wondering if you had run into anything like this?

**Comment by wshirey** [comment]
Jeremy, it's been almost a year and half since I did this course and I wish my memory was good enough to remember! Feel free to clone and compare.

**Comment by JeremyCarlsten** [comment]
No worries, figured I would ask. Joe hasn't responded in a while either. 
Thanks!
